version: '3.8'

services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}   # built by Jenkins
    # simply starts containers using the image already built by Jenkins
    ports:
      - "8081:8080" # map container port 8080 to host port 8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/network_performance
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      # tells Spring Boot where Kafka is running inside Docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - mysql
      - kafka

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      # Creates a database named network_performance on startup
      MYSQL_DATABASE: network_performance
    ports:
      # Maps MySQL container’s port 3306 to host machine’s port 3306,
      # so you can connect from outside Docker (e.g. IDE or tools)
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql # everything MySQL server needs to restore its state

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181" # Exposes Zookeeper’s client port 2181 to the host machine
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes" # allow connections without authentication

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092" # Exposes Kafka’s broker port to the host
    environment:
      KAFKA_BROKER_ID: 1 # A unique ID for this Kafka broker
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092 # Where Kafka listens for connections inside the container
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 # What Kafka tells clients to use to connect
      ALLOW_PLAINTEXT_LISTENER: "yes" # plaintext (non-SSL)
    depends_on:
      - zookeeper

volumes:
  mysql-data:
