version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080" # map container port 8080 to host port 8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/yourdbname
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      # Maps MySQL container’s port 3306 to your host machine’s port 3306,
      # so you can connect from outside Docker (e.g., your IDE or tools)
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
