server:
  port: 8081
  error:
    include-stacktrace: always
    include-message: always

spring:
  show-sql: true
  profiles:
    active: h2 # Change this to 'mysql' for production, 'h2' for development

