spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/network_performance
    url: jdbc:mysql://mysql:3306/network_performance
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root  # change as necessary

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true